/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersUserIdLogoutPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersUserIdLogoutPost200ResponseData{}

// UsersUserIdLogoutPost200ResponseData Response data from logging out a user.
type UsersUserIdLogoutPost200ResponseData struct {
	// Whether SSO logout was initiated.
	SsoLogout bool `json:"sso_logout"`
	// URL to redirect the user browser to for IdP session logout.
	SsoLogoutUrl *string `json:"sso_logout_url,omitempty"`
	// Warning message if SSO logout could not be performed.
	Warning *string `json:"warning,omitempty"`
}

type _UsersUserIdLogoutPost200ResponseData UsersUserIdLogoutPost200ResponseData

// NewUsersUserIdLogoutPost200ResponseData instantiates a new UsersUserIdLogoutPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersUserIdLogoutPost200ResponseData(ssoLogout bool) *UsersUserIdLogoutPost200ResponseData {
	this := UsersUserIdLogoutPost200ResponseData{}
	this.SsoLogout = ssoLogout
	return &this
}

// NewUsersUserIdLogoutPost200ResponseDataWithDefaults instantiates a new UsersUserIdLogoutPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersUserIdLogoutPost200ResponseDataWithDefaults() *UsersUserIdLogoutPost200ResponseData {
	this := UsersUserIdLogoutPost200ResponseData{}
	return &this
}

// GetSsoLogout returns the SsoLogout field value
func (o *UsersUserIdLogoutPost200ResponseData) GetSsoLogout() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SsoLogout
}

// GetSsoLogoutOk returns a tuple with the SsoLogout field value
// and a boolean to check if the value has been set.
func (o *UsersUserIdLogoutPost200ResponseData) GetSsoLogoutOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SsoLogout, true
}

// SetSsoLogout sets field value
func (o *UsersUserIdLogoutPost200ResponseData) SetSsoLogout(v bool) {
	o.SsoLogout = v
}

// GetSsoLogoutUrl returns the SsoLogoutUrl field value if set, zero value otherwise.
func (o *UsersUserIdLogoutPost200ResponseData) GetSsoLogoutUrl() string {
	if o == nil || IsNil(o.SsoLogoutUrl) {
		var ret string
		return ret
	}
	return *o.SsoLogoutUrl
}

// GetSsoLogoutUrlOk returns a tuple with the SsoLogoutUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserIdLogoutPost200ResponseData) GetSsoLogoutUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SsoLogoutUrl) {
		return nil, false
	}
	return o.SsoLogoutUrl, true
}

// HasSsoLogoutUrl returns a boolean if a field has been set.
func (o *UsersUserIdLogoutPost200ResponseData) HasSsoLogoutUrl() bool {
	if o != nil && !IsNil(o.SsoLogoutUrl) {
		return true
	}

	return false
}

// SetSsoLogoutUrl gets a reference to the given string and assigns it to the SsoLogoutUrl field.
func (o *UsersUserIdLogoutPost200ResponseData) SetSsoLogoutUrl(v string) {
	o.SsoLogoutUrl = &v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *UsersUserIdLogoutPost200ResponseData) GetWarning() string {
	if o == nil || IsNil(o.Warning) {
		var ret string
		return ret
	}
	return *o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersUserIdLogoutPost200ResponseData) GetWarningOk() (*string, bool) {
	if o == nil || IsNil(o.Warning) {
		return nil, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *UsersUserIdLogoutPost200ResponseData) HasWarning() bool {
	if o != nil && !IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given string and assigns it to the Warning field.
func (o *UsersUserIdLogoutPost200ResponseData) SetWarning(v string) {
	o.Warning = &v
}

func (o UsersUserIdLogoutPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersUserIdLogoutPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sso_logout"] = o.SsoLogout
	if !IsNil(o.SsoLogoutUrl) {
		toSerialize["sso_logout_url"] = o.SsoLogoutUrl
	}
	if !IsNil(o.Warning) {
		toSerialize["warning"] = o.Warning
	}
	return toSerialize, nil
}

func (o *UsersUserIdLogoutPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sso_logout",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersUserIdLogoutPost200ResponseData := _UsersUserIdLogoutPost200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersUserIdLogoutPost200ResponseData)

	if err != nil {
		return err
	}

	*o = UsersUserIdLogoutPost200ResponseData(varUsersUserIdLogoutPost200ResponseData)

	return err
}

type NullableUsersUserIdLogoutPost200ResponseData struct {
	value *UsersUserIdLogoutPost200ResponseData
	isSet bool
}

func (v NullableUsersUserIdLogoutPost200ResponseData) Get() *UsersUserIdLogoutPost200ResponseData {
	return v.value
}

func (v *NullableUsersUserIdLogoutPost200ResponseData) Set(val *UsersUserIdLogoutPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersUserIdLogoutPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersUserIdLogoutPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersUserIdLogoutPost200ResponseData(val *UsersUserIdLogoutPost200ResponseData) *NullableUsersUserIdLogoutPost200ResponseData {
	return &NullableUsersUserIdLogoutPost200ResponseData{value: val, isSet: true}
}

func (v NullableUsersUserIdLogoutPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersUserIdLogoutPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


