/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IpAllowlist type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpAllowlist{}

// IpAllowlist struct for IpAllowlist
type IpAllowlist struct {
	IpAddresses InfoIpAllowlistGet200ResponseDataIpAddresses `json:"ipAddresses"`
}

type _IpAllowlist IpAllowlist

// NewIpAllowlist instantiates a new IpAllowlist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpAllowlist(ipAddresses InfoIpAllowlistGet200ResponseDataIpAddresses) *IpAllowlist {
	this := IpAllowlist{}
	this.IpAddresses = ipAddresses
	return &this
}

// NewIpAllowlistWithDefaults instantiates a new IpAllowlist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpAllowlistWithDefaults() *IpAllowlist {
	this := IpAllowlist{}
	return &this
}

// GetIpAddresses returns the IpAddresses field value
func (o *IpAllowlist) GetIpAddresses() InfoIpAllowlistGet200ResponseDataIpAddresses {
	if o == nil {
		var ret InfoIpAllowlistGet200ResponseDataIpAddresses
		return ret
	}

	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value
// and a boolean to check if the value has been set.
func (o *IpAllowlist) GetIpAddressesOk() (*InfoIpAllowlistGet200ResponseDataIpAddresses, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddresses, true
}

// SetIpAddresses sets field value
func (o *IpAllowlist) SetIpAddresses(v InfoIpAllowlistGet200ResponseDataIpAddresses) {
	o.IpAddresses = v
}

func (o IpAllowlist) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpAllowlist) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ipAddresses"] = o.IpAddresses
	return toSerialize, nil
}

func (o *IpAllowlist) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ipAddresses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpAllowlist := _IpAllowlist{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIpAllowlist)

	if err != nil {
		return err
	}

	*o = IpAllowlist(varIpAllowlist)

	return err
}

type NullableIpAllowlist struct {
	value *IpAllowlist
	isSet bool
}

func (v NullableIpAllowlist) Get() *IpAllowlist {
	return v.value
}

func (v *NullableIpAllowlist) Set(val *IpAllowlist) {
	v.value = val
	v.isSet = true
}

func (v NullableIpAllowlist) IsSet() bool {
	return v.isSet
}

func (v *NullableIpAllowlist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpAllowlist(val *IpAllowlist) *NullableIpAllowlist {
	return &NullableIpAllowlist{value: val, isSet: true}
}

func (v NullableIpAllowlist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpAllowlist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


