/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SnowflakeOptionsAuthenticationOptionsAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnowflakeOptionsAuthenticationOptionsAnyOf{}

// SnowflakeOptionsAuthenticationOptionsAnyOf struct for SnowflakeOptionsAuthenticationOptionsAnyOf
type SnowflakeOptionsAuthenticationOptionsAnyOf struct {
	AuthenticationType string `json:"authentication_type"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type _SnowflakeOptionsAuthenticationOptionsAnyOf SnowflakeOptionsAuthenticationOptionsAnyOf

// NewSnowflakeOptionsAuthenticationOptionsAnyOf instantiates a new SnowflakeOptionsAuthenticationOptionsAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnowflakeOptionsAuthenticationOptionsAnyOf(authenticationType string, username string, password string) *SnowflakeOptionsAuthenticationOptionsAnyOf {
	this := SnowflakeOptionsAuthenticationOptionsAnyOf{}
	this.AuthenticationType = authenticationType
	this.Username = username
	this.Password = password
	return &this
}

// NewSnowflakeOptionsAuthenticationOptionsAnyOfWithDefaults instantiates a new SnowflakeOptionsAuthenticationOptionsAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnowflakeOptionsAuthenticationOptionsAnyOfWithDefaults() *SnowflakeOptionsAuthenticationOptionsAnyOf {
	this := SnowflakeOptionsAuthenticationOptionsAnyOf{}
	return &this
}

// GetAuthenticationType returns the AuthenticationType field value
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) GetAuthenticationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationType
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value
// and a boolean to check if the value has been set.
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) GetAuthenticationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationType, true
}

// SetAuthenticationType sets field value
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) SetAuthenticationType(v string) {
	o.AuthenticationType = v
}

// GetUsername returns the Username field value
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) SetPassword(v string) {
	o.Password = v
}

func (o SnowflakeOptionsAuthenticationOptionsAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnowflakeOptionsAuthenticationOptionsAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authentication_type"] = o.AuthenticationType
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *SnowflakeOptionsAuthenticationOptionsAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authentication_type",
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnowflakeOptionsAuthenticationOptionsAnyOf := _SnowflakeOptionsAuthenticationOptionsAnyOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnowflakeOptionsAuthenticationOptionsAnyOf)

	if err != nil {
		return err
	}

	*o = SnowflakeOptionsAuthenticationOptionsAnyOf(varSnowflakeOptionsAuthenticationOptionsAnyOf)

	return err
}

type NullableSnowflakeOptionsAuthenticationOptionsAnyOf struct {
	value *SnowflakeOptionsAuthenticationOptionsAnyOf
	isSet bool
}

func (v NullableSnowflakeOptionsAuthenticationOptionsAnyOf) Get() *SnowflakeOptionsAuthenticationOptionsAnyOf {
	return v.value
}

func (v *NullableSnowflakeOptionsAuthenticationOptionsAnyOf) Set(val *SnowflakeOptionsAuthenticationOptionsAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSnowflakeOptionsAuthenticationOptionsAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSnowflakeOptionsAuthenticationOptionsAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnowflakeOptionsAuthenticationOptionsAnyOf(val *SnowflakeOptionsAuthenticationOptionsAnyOf) *NullableSnowflakeOptionsAuthenticationOptionsAnyOf {
	return &NullableSnowflakeOptionsAuthenticationOptionsAnyOf{value: val, isSet: true}
}

func (v NullableSnowflakeOptionsAuthenticationOptionsAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnowflakeOptionsAuthenticationOptionsAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


