/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SourceControlBranchesPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceControlBranchesPost200ResponseData{}

// SourceControlBranchesPost200ResponseData Source control create app branch response
type SourceControlBranchesPost200ResponseData struct {
	// The created Retool branch ID.
	BranchId string `json:"branch_id"`
	// The created Retool branch name.
	BranchName string `json:"branch_name"`
	// Whether the branch is shared with other users.
	Shared bool `json:"shared"`
	Element NullableSourceControlBranchesPost200ResponseDataElement `json:"element"`
	AdditionalProperties map[string]interface{}
}

type _SourceControlBranchesPost200ResponseData SourceControlBranchesPost200ResponseData

// NewSourceControlBranchesPost200ResponseData instantiates a new SourceControlBranchesPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceControlBranchesPost200ResponseData(branchId string, branchName string, shared bool, element NullableSourceControlBranchesPost200ResponseDataElement) *SourceControlBranchesPost200ResponseData {
	this := SourceControlBranchesPost200ResponseData{}
	this.BranchId = branchId
	this.BranchName = branchName
	this.Shared = shared
	this.Element = element
	return &this
}

// NewSourceControlBranchesPost200ResponseDataWithDefaults instantiates a new SourceControlBranchesPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceControlBranchesPost200ResponseDataWithDefaults() *SourceControlBranchesPost200ResponseData {
	this := SourceControlBranchesPost200ResponseData{}
	return &this
}

// GetBranchId returns the BranchId field value
func (o *SourceControlBranchesPost200ResponseData) GetBranchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BranchId
}

// GetBranchIdOk returns a tuple with the BranchId field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesPost200ResponseData) GetBranchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BranchId, true
}

// SetBranchId sets field value
func (o *SourceControlBranchesPost200ResponseData) SetBranchId(v string) {
	o.BranchId = v
}

// GetBranchName returns the BranchName field value
func (o *SourceControlBranchesPost200ResponseData) GetBranchName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BranchName
}

// GetBranchNameOk returns a tuple with the BranchName field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesPost200ResponseData) GetBranchNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BranchName, true
}

// SetBranchName sets field value
func (o *SourceControlBranchesPost200ResponseData) SetBranchName(v string) {
	o.BranchName = v
}

// GetShared returns the Shared field value
func (o *SourceControlBranchesPost200ResponseData) GetShared() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Shared
}

// GetSharedOk returns a tuple with the Shared field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesPost200ResponseData) GetSharedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Shared, true
}

// SetShared sets field value
func (o *SourceControlBranchesPost200ResponseData) SetShared(v bool) {
	o.Shared = v
}

// GetElement returns the Element field value
// If the value is explicit nil, the zero value for SourceControlBranchesPost200ResponseDataElement will be returned
func (o *SourceControlBranchesPost200ResponseData) GetElement() SourceControlBranchesPost200ResponseDataElement {
	if o == nil || o.Element.Get() == nil {
		var ret SourceControlBranchesPost200ResponseDataElement
		return ret
	}

	return *o.Element.Get()
}

// GetElementOk returns a tuple with the Element field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceControlBranchesPost200ResponseData) GetElementOk() (*SourceControlBranchesPost200ResponseDataElement, bool) {
	if o == nil {
		return nil, false
	}
	return o.Element.Get(), o.Element.IsSet()
}

// SetElement sets field value
func (o *SourceControlBranchesPost200ResponseData) SetElement(v SourceControlBranchesPost200ResponseDataElement) {
	o.Element.Set(&v)
}

func (o SourceControlBranchesPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceControlBranchesPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["branch_id"] = o.BranchId
	toSerialize["branch_name"] = o.BranchName
	toSerialize["shared"] = o.Shared
	toSerialize["element"] = o.Element.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SourceControlBranchesPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"branch_id",
		"branch_name",
		"shared",
		"element",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceControlBranchesPost200ResponseData := _SourceControlBranchesPost200ResponseData{}

	err = json.Unmarshal(data, &varSourceControlBranchesPost200ResponseData)

	if err != nil {
		return err
	}

	*o = SourceControlBranchesPost200ResponseData(varSourceControlBranchesPost200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "branch_id")
		delete(additionalProperties, "branch_name")
		delete(additionalProperties, "shared")
		delete(additionalProperties, "element")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSourceControlBranchesPost200ResponseData struct {
	value *SourceControlBranchesPost200ResponseData
	isSet bool
}

func (v NullableSourceControlBranchesPost200ResponseData) Get() *SourceControlBranchesPost200ResponseData {
	return v.value
}

func (v *NullableSourceControlBranchesPost200ResponseData) Set(val *SourceControlBranchesPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlBranchesPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlBranchesPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlBranchesPost200ResponseData(val *SourceControlBranchesPost200ResponseData) *NullableSourceControlBranchesPost200ResponseData {
	return &NullableSourceControlBranchesPost200ResponseData{value: val, isSet: true}
}

func (v NullableSourceControlBranchesPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlBranchesPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


