/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SourceControlBranchesResetPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceControlBranchesResetPost200ResponseData{}

// SourceControlBranchesResetPost200ResponseData Source control reset app branch response
type SourceControlBranchesResetPost200ResponseData struct {
	// The Retool app branch that was reset.
	BranchName string `json:"branch_name"`
	// The remote Git branch used as the reset source.
	RemoteBranchName string `json:"remote_branch_name"`
	// The reset result.
	Status string `json:"status"`
	// Apps that were reset from the remote branch.
	UpdatedApps []SourceControlBranchesResetPost200ResponseDataUpdatedAppsInner `json:"updated_apps"`
	AdditionalProperties map[string]interface{}
}

type _SourceControlBranchesResetPost200ResponseData SourceControlBranchesResetPost200ResponseData

// NewSourceControlBranchesResetPost200ResponseData instantiates a new SourceControlBranchesResetPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceControlBranchesResetPost200ResponseData(branchName string, remoteBranchName string, status string, updatedApps []SourceControlBranchesResetPost200ResponseDataUpdatedAppsInner) *SourceControlBranchesResetPost200ResponseData {
	this := SourceControlBranchesResetPost200ResponseData{}
	this.BranchName = branchName
	this.RemoteBranchName = remoteBranchName
	this.Status = status
	this.UpdatedApps = updatedApps
	return &this
}

// NewSourceControlBranchesResetPost200ResponseDataWithDefaults instantiates a new SourceControlBranchesResetPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceControlBranchesResetPost200ResponseDataWithDefaults() *SourceControlBranchesResetPost200ResponseData {
	this := SourceControlBranchesResetPost200ResponseData{}
	return &this
}

// GetBranchName returns the BranchName field value
func (o *SourceControlBranchesResetPost200ResponseData) GetBranchName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BranchName
}

// GetBranchNameOk returns a tuple with the BranchName field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesResetPost200ResponseData) GetBranchNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BranchName, true
}

// SetBranchName sets field value
func (o *SourceControlBranchesResetPost200ResponseData) SetBranchName(v string) {
	o.BranchName = v
}

// GetRemoteBranchName returns the RemoteBranchName field value
func (o *SourceControlBranchesResetPost200ResponseData) GetRemoteBranchName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteBranchName
}

// GetRemoteBranchNameOk returns a tuple with the RemoteBranchName field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesResetPost200ResponseData) GetRemoteBranchNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteBranchName, true
}

// SetRemoteBranchName sets field value
func (o *SourceControlBranchesResetPost200ResponseData) SetRemoteBranchName(v string) {
	o.RemoteBranchName = v
}

// GetStatus returns the Status field value
func (o *SourceControlBranchesResetPost200ResponseData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesResetPost200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SourceControlBranchesResetPost200ResponseData) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedApps returns the UpdatedApps field value
func (o *SourceControlBranchesResetPost200ResponseData) GetUpdatedApps() []SourceControlBranchesResetPost200ResponseDataUpdatedAppsInner {
	if o == nil {
		var ret []SourceControlBranchesResetPost200ResponseDataUpdatedAppsInner
		return ret
	}

	return o.UpdatedApps
}

// GetUpdatedAppsOk returns a tuple with the UpdatedApps field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesResetPost200ResponseData) GetUpdatedAppsOk() ([]SourceControlBranchesResetPost200ResponseDataUpdatedAppsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedApps, true
}

// SetUpdatedApps sets field value
func (o *SourceControlBranchesResetPost200ResponseData) SetUpdatedApps(v []SourceControlBranchesResetPost200ResponseDataUpdatedAppsInner) {
	o.UpdatedApps = v
}

func (o SourceControlBranchesResetPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceControlBranchesResetPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["branch_name"] = o.BranchName
	toSerialize["remote_branch_name"] = o.RemoteBranchName
	toSerialize["status"] = o.Status
	toSerialize["updated_apps"] = o.UpdatedApps

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SourceControlBranchesResetPost200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"branch_name",
		"remote_branch_name",
		"status",
		"updated_apps",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceControlBranchesResetPost200ResponseData := _SourceControlBranchesResetPost200ResponseData{}

	err = json.Unmarshal(data, &varSourceControlBranchesResetPost200ResponseData)

	if err != nil {
		return err
	}

	*o = SourceControlBranchesResetPost200ResponseData(varSourceControlBranchesResetPost200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "branch_name")
		delete(additionalProperties, "remote_branch_name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "updated_apps")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSourceControlBranchesResetPost200ResponseData struct {
	value *SourceControlBranchesResetPost200ResponseData
	isSet bool
}

func (v NullableSourceControlBranchesResetPost200ResponseData) Get() *SourceControlBranchesResetPost200ResponseData {
	return v.value
}

func (v *NullableSourceControlBranchesResetPost200ResponseData) Set(val *SourceControlBranchesResetPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlBranchesResetPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlBranchesResetPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlBranchesResetPost200ResponseData(val *SourceControlBranchesResetPost200ResponseData) *NullableSourceControlBranchesResetPost200ResponseData {
	return &NullableSourceControlBranchesResetPost200ResponseData{value: val, isSet: true}
}

func (v NullableSourceControlBranchesResetPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlBranchesResetPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


