/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SourceControlReleasesAppsAppUuidGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceControlReleasesAppsAppUuidGet200Response{}

// SourceControlReleasesAppsAppUuidGet200Response struct for SourceControlReleasesAppsAppUuidGet200Response
type SourceControlReleasesAppsAppUuidGet200Response struct {
	// API request succeeded
	Success bool `json:"success"`
	Data []SourceControlReleasesAppsAppUuidGet200ResponseDataInner `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SourceControlReleasesAppsAppUuidGet200Response SourceControlReleasesAppsAppUuidGet200Response

// NewSourceControlReleasesAppsAppUuidGet200Response instantiates a new SourceControlReleasesAppsAppUuidGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceControlReleasesAppsAppUuidGet200Response(success bool, data []SourceControlReleasesAppsAppUuidGet200ResponseDataInner) *SourceControlReleasesAppsAppUuidGet200Response {
	this := SourceControlReleasesAppsAppUuidGet200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewSourceControlReleasesAppsAppUuidGet200ResponseWithDefaults instantiates a new SourceControlReleasesAppsAppUuidGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceControlReleasesAppsAppUuidGet200ResponseWithDefaults() *SourceControlReleasesAppsAppUuidGet200Response {
	this := SourceControlReleasesAppsAppUuidGet200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *SourceControlReleasesAppsAppUuidGet200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *SourceControlReleasesAppsAppUuidGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *SourceControlReleasesAppsAppUuidGet200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *SourceControlReleasesAppsAppUuidGet200Response) GetData() []SourceControlReleasesAppsAppUuidGet200ResponseDataInner {
	if o == nil {
		var ret []SourceControlReleasesAppsAppUuidGet200ResponseDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SourceControlReleasesAppsAppUuidGet200Response) GetDataOk() ([]SourceControlReleasesAppsAppUuidGet200ResponseDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SourceControlReleasesAppsAppUuidGet200Response) SetData(v []SourceControlReleasesAppsAppUuidGet200ResponseDataInner) {
	o.Data = v
}

func (o SourceControlReleasesAppsAppUuidGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceControlReleasesAppsAppUuidGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SourceControlReleasesAppsAppUuidGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceControlReleasesAppsAppUuidGet200Response := _SourceControlReleasesAppsAppUuidGet200Response{}

	err = json.Unmarshal(data, &varSourceControlReleasesAppsAppUuidGet200Response)

	if err != nil {
		return err
	}

	*o = SourceControlReleasesAppsAppUuidGet200Response(varSourceControlReleasesAppsAppUuidGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSourceControlReleasesAppsAppUuidGet200Response struct {
	value *SourceControlReleasesAppsAppUuidGet200Response
	isSet bool
}

func (v NullableSourceControlReleasesAppsAppUuidGet200Response) Get() *SourceControlReleasesAppsAppUuidGet200Response {
	return v.value
}

func (v *NullableSourceControlReleasesAppsAppUuidGet200Response) Set(val *SourceControlReleasesAppsAppUuidGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlReleasesAppsAppUuidGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlReleasesAppsAppUuidGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlReleasesAppsAppUuidGet200Response(val *SourceControlReleasesAppsAppUuidGet200Response) *NullableSourceControlReleasesAppsAppUuidGet200Response {
	return &NullableSourceControlReleasesAppsAppUuidGet200Response{value: val, isSet: true}
}

func (v NullableSourceControlReleasesAppsAppUuidGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlReleasesAppsAppUuidGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


