/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoogleSAML type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoogleSAML{}

// GoogleSAML struct for GoogleSAML
type GoogleSAML struct {
	ConfigType string `json:"config_type"`
	GoogleClientId string `json:"google_client_id"`
	GoogleClientSecret string `json:"google_client_secret"`
	DisableEmailPasswordLogin bool `json:"disable_email_password_login"`
	IdpMetadataXml string `json:"idp_metadata_xml"`
	SamlFirstNameAttribute string `json:"saml_first_name_attribute"`
	SamlLastNameAttribute string `json:"saml_last_name_attribute"`
	SamlGroupsAttribute *string `json:"saml_groups_attribute,omitempty"`
	SamlSyncGroupClaims bool `json:"saml_sync_group_claims"`
	LdapSyncGroupClaims *bool `json:"ldap_sync_group_claims,omitempty"`
	LdapRoleMapping *string `json:"ldap_role_mapping,omitempty"`
	LdapServerUrl *string `json:"ldap_server_url,omitempty"`
	LdapBaseDomainComponents *string `json:"ldap_base_domain_components,omitempty"`
	LdapServerName *string `json:"ldap_server_name,omitempty"`
	LdapServerKey *string `json:"ldap_server_key,omitempty"`
	LdapServerCertificate *string `json:"ldap_server_certificate,omitempty"`
	JitEnabled bool `json:"jit_enabled"`
	RestrictedDomain *string `json:"restricted_domain,omitempty"`
	TriggerLoginAutomatically bool `json:"trigger_login_automatically"`
}

type _GoogleSAML GoogleSAML

// NewGoogleSAML instantiates a new GoogleSAML object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleSAML(configType string, googleClientId string, googleClientSecret string, disableEmailPasswordLogin bool, idpMetadataXml string, samlFirstNameAttribute string, samlLastNameAttribute string, samlSyncGroupClaims bool, jitEnabled bool, triggerLoginAutomatically bool) *GoogleSAML {
	this := GoogleSAML{}
	this.ConfigType = configType
	this.GoogleClientId = googleClientId
	this.GoogleClientSecret = googleClientSecret
	this.DisableEmailPasswordLogin = disableEmailPasswordLogin
	this.IdpMetadataXml = idpMetadataXml
	this.SamlFirstNameAttribute = samlFirstNameAttribute
	this.SamlLastNameAttribute = samlLastNameAttribute
	this.SamlSyncGroupClaims = samlSyncGroupClaims
	this.JitEnabled = jitEnabled
	this.TriggerLoginAutomatically = triggerLoginAutomatically
	return &this
}

// NewGoogleSAMLWithDefaults instantiates a new GoogleSAML object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleSAMLWithDefaults() *GoogleSAML {
	this := GoogleSAML{}
	return &this
}

// GetConfigType returns the ConfigType field value
func (o *GoogleSAML) GetConfigType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfigType
}

// GetConfigTypeOk returns a tuple with the ConfigType field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetConfigTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigType, true
}

// SetConfigType sets field value
func (o *GoogleSAML) SetConfigType(v string) {
	o.ConfigType = v
}

// GetGoogleClientId returns the GoogleClientId field value
func (o *GoogleSAML) GetGoogleClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GoogleClientId
}

// GetGoogleClientIdOk returns a tuple with the GoogleClientId field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetGoogleClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GoogleClientId, true
}

// SetGoogleClientId sets field value
func (o *GoogleSAML) SetGoogleClientId(v string) {
	o.GoogleClientId = v
}

// GetGoogleClientSecret returns the GoogleClientSecret field value
func (o *GoogleSAML) GetGoogleClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GoogleClientSecret
}

// GetGoogleClientSecretOk returns a tuple with the GoogleClientSecret field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetGoogleClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GoogleClientSecret, true
}

// SetGoogleClientSecret sets field value
func (o *GoogleSAML) SetGoogleClientSecret(v string) {
	o.GoogleClientSecret = v
}

// GetDisableEmailPasswordLogin returns the DisableEmailPasswordLogin field value
func (o *GoogleSAML) GetDisableEmailPasswordLogin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DisableEmailPasswordLogin
}

// GetDisableEmailPasswordLoginOk returns a tuple with the DisableEmailPasswordLogin field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetDisableEmailPasswordLoginOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisableEmailPasswordLogin, true
}

// SetDisableEmailPasswordLogin sets field value
func (o *GoogleSAML) SetDisableEmailPasswordLogin(v bool) {
	o.DisableEmailPasswordLogin = v
}

// GetIdpMetadataXml returns the IdpMetadataXml field value
func (o *GoogleSAML) GetIdpMetadataXml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdpMetadataXml
}

// GetIdpMetadataXmlOk returns a tuple with the IdpMetadataXml field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetIdpMetadataXmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdpMetadataXml, true
}

// SetIdpMetadataXml sets field value
func (o *GoogleSAML) SetIdpMetadataXml(v string) {
	o.IdpMetadataXml = v
}

// GetSamlFirstNameAttribute returns the SamlFirstNameAttribute field value
func (o *GoogleSAML) GetSamlFirstNameAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SamlFirstNameAttribute
}

// GetSamlFirstNameAttributeOk returns a tuple with the SamlFirstNameAttribute field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetSamlFirstNameAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SamlFirstNameAttribute, true
}

// SetSamlFirstNameAttribute sets field value
func (o *GoogleSAML) SetSamlFirstNameAttribute(v string) {
	o.SamlFirstNameAttribute = v
}

// GetSamlLastNameAttribute returns the SamlLastNameAttribute field value
func (o *GoogleSAML) GetSamlLastNameAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SamlLastNameAttribute
}

// GetSamlLastNameAttributeOk returns a tuple with the SamlLastNameAttribute field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetSamlLastNameAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SamlLastNameAttribute, true
}

// SetSamlLastNameAttribute sets field value
func (o *GoogleSAML) SetSamlLastNameAttribute(v string) {
	o.SamlLastNameAttribute = v
}

// GetSamlGroupsAttribute returns the SamlGroupsAttribute field value if set, zero value otherwise.
func (o *GoogleSAML) GetSamlGroupsAttribute() string {
	if o == nil || IsNil(o.SamlGroupsAttribute) {
		var ret string
		return ret
	}
	return *o.SamlGroupsAttribute
}

// GetSamlGroupsAttributeOk returns a tuple with the SamlGroupsAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetSamlGroupsAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.SamlGroupsAttribute) {
		return nil, false
	}
	return o.SamlGroupsAttribute, true
}

// HasSamlGroupsAttribute returns a boolean if a field has been set.
func (o *GoogleSAML) HasSamlGroupsAttribute() bool {
	if o != nil && !IsNil(o.SamlGroupsAttribute) {
		return true
	}

	return false
}

// SetSamlGroupsAttribute gets a reference to the given string and assigns it to the SamlGroupsAttribute field.
func (o *GoogleSAML) SetSamlGroupsAttribute(v string) {
	o.SamlGroupsAttribute = &v
}

// GetSamlSyncGroupClaims returns the SamlSyncGroupClaims field value
func (o *GoogleSAML) GetSamlSyncGroupClaims() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SamlSyncGroupClaims
}

// GetSamlSyncGroupClaimsOk returns a tuple with the SamlSyncGroupClaims field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetSamlSyncGroupClaimsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SamlSyncGroupClaims, true
}

// SetSamlSyncGroupClaims sets field value
func (o *GoogleSAML) SetSamlSyncGroupClaims(v bool) {
	o.SamlSyncGroupClaims = v
}

// GetLdapSyncGroupClaims returns the LdapSyncGroupClaims field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapSyncGroupClaims() bool {
	if o == nil || IsNil(o.LdapSyncGroupClaims) {
		var ret bool
		return ret
	}
	return *o.LdapSyncGroupClaims
}

// GetLdapSyncGroupClaimsOk returns a tuple with the LdapSyncGroupClaims field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapSyncGroupClaimsOk() (*bool, bool) {
	if o == nil || IsNil(o.LdapSyncGroupClaims) {
		return nil, false
	}
	return o.LdapSyncGroupClaims, true
}

// HasLdapSyncGroupClaims returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapSyncGroupClaims() bool {
	if o != nil && !IsNil(o.LdapSyncGroupClaims) {
		return true
	}

	return false
}

// SetLdapSyncGroupClaims gets a reference to the given bool and assigns it to the LdapSyncGroupClaims field.
func (o *GoogleSAML) SetLdapSyncGroupClaims(v bool) {
	o.LdapSyncGroupClaims = &v
}

// GetLdapRoleMapping returns the LdapRoleMapping field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapRoleMapping() string {
	if o == nil || IsNil(o.LdapRoleMapping) {
		var ret string
		return ret
	}
	return *o.LdapRoleMapping
}

// GetLdapRoleMappingOk returns a tuple with the LdapRoleMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapRoleMappingOk() (*string, bool) {
	if o == nil || IsNil(o.LdapRoleMapping) {
		return nil, false
	}
	return o.LdapRoleMapping, true
}

// HasLdapRoleMapping returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapRoleMapping() bool {
	if o != nil && !IsNil(o.LdapRoleMapping) {
		return true
	}

	return false
}

// SetLdapRoleMapping gets a reference to the given string and assigns it to the LdapRoleMapping field.
func (o *GoogleSAML) SetLdapRoleMapping(v string) {
	o.LdapRoleMapping = &v
}

// GetLdapServerUrl returns the LdapServerUrl field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapServerUrl() string {
	if o == nil || IsNil(o.LdapServerUrl) {
		var ret string
		return ret
	}
	return *o.LdapServerUrl
}

// GetLdapServerUrlOk returns a tuple with the LdapServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapServerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LdapServerUrl) {
		return nil, false
	}
	return o.LdapServerUrl, true
}

// HasLdapServerUrl returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapServerUrl() bool {
	if o != nil && !IsNil(o.LdapServerUrl) {
		return true
	}

	return false
}

// SetLdapServerUrl gets a reference to the given string and assigns it to the LdapServerUrl field.
func (o *GoogleSAML) SetLdapServerUrl(v string) {
	o.LdapServerUrl = &v
}

// GetLdapBaseDomainComponents returns the LdapBaseDomainComponents field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapBaseDomainComponents() string {
	if o == nil || IsNil(o.LdapBaseDomainComponents) {
		var ret string
		return ret
	}
	return *o.LdapBaseDomainComponents
}

// GetLdapBaseDomainComponentsOk returns a tuple with the LdapBaseDomainComponents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapBaseDomainComponentsOk() (*string, bool) {
	if o == nil || IsNil(o.LdapBaseDomainComponents) {
		return nil, false
	}
	return o.LdapBaseDomainComponents, true
}

// HasLdapBaseDomainComponents returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapBaseDomainComponents() bool {
	if o != nil && !IsNil(o.LdapBaseDomainComponents) {
		return true
	}

	return false
}

// SetLdapBaseDomainComponents gets a reference to the given string and assigns it to the LdapBaseDomainComponents field.
func (o *GoogleSAML) SetLdapBaseDomainComponents(v string) {
	o.LdapBaseDomainComponents = &v
}

// GetLdapServerName returns the LdapServerName field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapServerName() string {
	if o == nil || IsNil(o.LdapServerName) {
		var ret string
		return ret
	}
	return *o.LdapServerName
}

// GetLdapServerNameOk returns a tuple with the LdapServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.LdapServerName) {
		return nil, false
	}
	return o.LdapServerName, true
}

// HasLdapServerName returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapServerName() bool {
	if o != nil && !IsNil(o.LdapServerName) {
		return true
	}

	return false
}

// SetLdapServerName gets a reference to the given string and assigns it to the LdapServerName field.
func (o *GoogleSAML) SetLdapServerName(v string) {
	o.LdapServerName = &v
}

// GetLdapServerKey returns the LdapServerKey field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapServerKey() string {
	if o == nil || IsNil(o.LdapServerKey) {
		var ret string
		return ret
	}
	return *o.LdapServerKey
}

// GetLdapServerKeyOk returns a tuple with the LdapServerKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapServerKeyOk() (*string, bool) {
	if o == nil || IsNil(o.LdapServerKey) {
		return nil, false
	}
	return o.LdapServerKey, true
}

// HasLdapServerKey returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapServerKey() bool {
	if o != nil && !IsNil(o.LdapServerKey) {
		return true
	}

	return false
}

// SetLdapServerKey gets a reference to the given string and assigns it to the LdapServerKey field.
func (o *GoogleSAML) SetLdapServerKey(v string) {
	o.LdapServerKey = &v
}

// GetLdapServerCertificate returns the LdapServerCertificate field value if set, zero value otherwise.
func (o *GoogleSAML) GetLdapServerCertificate() string {
	if o == nil || IsNil(o.LdapServerCertificate) {
		var ret string
		return ret
	}
	return *o.LdapServerCertificate
}

// GetLdapServerCertificateOk returns a tuple with the LdapServerCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetLdapServerCertificateOk() (*string, bool) {
	if o == nil || IsNil(o.LdapServerCertificate) {
		return nil, false
	}
	return o.LdapServerCertificate, true
}

// HasLdapServerCertificate returns a boolean if a field has been set.
func (o *GoogleSAML) HasLdapServerCertificate() bool {
	if o != nil && !IsNil(o.LdapServerCertificate) {
		return true
	}

	return false
}

// SetLdapServerCertificate gets a reference to the given string and assigns it to the LdapServerCertificate field.
func (o *GoogleSAML) SetLdapServerCertificate(v string) {
	o.LdapServerCertificate = &v
}

// GetJitEnabled returns the JitEnabled field value
func (o *GoogleSAML) GetJitEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.JitEnabled
}

// GetJitEnabledOk returns a tuple with the JitEnabled field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetJitEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JitEnabled, true
}

// SetJitEnabled sets field value
func (o *GoogleSAML) SetJitEnabled(v bool) {
	o.JitEnabled = v
}

// GetRestrictedDomain returns the RestrictedDomain field value if set, zero value otherwise.
func (o *GoogleSAML) GetRestrictedDomain() string {
	if o == nil || IsNil(o.RestrictedDomain) {
		var ret string
		return ret
	}
	return *o.RestrictedDomain
}

// GetRestrictedDomainOk returns a tuple with the RestrictedDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetRestrictedDomainOk() (*string, bool) {
	if o == nil || IsNil(o.RestrictedDomain) {
		return nil, false
	}
	return o.RestrictedDomain, true
}

// HasRestrictedDomain returns a boolean if a field has been set.
func (o *GoogleSAML) HasRestrictedDomain() bool {
	if o != nil && !IsNil(o.RestrictedDomain) {
		return true
	}

	return false
}

// SetRestrictedDomain gets a reference to the given string and assigns it to the RestrictedDomain field.
func (o *GoogleSAML) SetRestrictedDomain(v string) {
	o.RestrictedDomain = &v
}

// GetTriggerLoginAutomatically returns the TriggerLoginAutomatically field value
func (o *GoogleSAML) GetTriggerLoginAutomatically() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TriggerLoginAutomatically
}

// GetTriggerLoginAutomaticallyOk returns a tuple with the TriggerLoginAutomatically field value
// and a boolean to check if the value has been set.
func (o *GoogleSAML) GetTriggerLoginAutomaticallyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TriggerLoginAutomatically, true
}

// SetTriggerLoginAutomatically sets field value
func (o *GoogleSAML) SetTriggerLoginAutomatically(v bool) {
	o.TriggerLoginAutomatically = v
}

func (o GoogleSAML) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoogleSAML) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["config_type"] = o.ConfigType
	toSerialize["google_client_id"] = o.GoogleClientId
	toSerialize["google_client_secret"] = o.GoogleClientSecret
	toSerialize["disable_email_password_login"] = o.DisableEmailPasswordLogin
	toSerialize["idp_metadata_xml"] = o.IdpMetadataXml
	toSerialize["saml_first_name_attribute"] = o.SamlFirstNameAttribute
	toSerialize["saml_last_name_attribute"] = o.SamlLastNameAttribute
	if !IsNil(o.SamlGroupsAttribute) {
		toSerialize["saml_groups_attribute"] = o.SamlGroupsAttribute
	}
	toSerialize["saml_sync_group_claims"] = o.SamlSyncGroupClaims
	if !IsNil(o.LdapSyncGroupClaims) {
		toSerialize["ldap_sync_group_claims"] = o.LdapSyncGroupClaims
	}
	if !IsNil(o.LdapRoleMapping) {
		toSerialize["ldap_role_mapping"] = o.LdapRoleMapping
	}
	if !IsNil(o.LdapServerUrl) {
		toSerialize["ldap_server_url"] = o.LdapServerUrl
	}
	if !IsNil(o.LdapBaseDomainComponents) {
		toSerialize["ldap_base_domain_components"] = o.LdapBaseDomainComponents
	}
	if !IsNil(o.LdapServerName) {
		toSerialize["ldap_server_name"] = o.LdapServerName
	}
	if !IsNil(o.LdapServerKey) {
		toSerialize["ldap_server_key"] = o.LdapServerKey
	}
	if !IsNil(o.LdapServerCertificate) {
		toSerialize["ldap_server_certificate"] = o.LdapServerCertificate
	}
	toSerialize["jit_enabled"] = o.JitEnabled
	if !IsNil(o.RestrictedDomain) {
		toSerialize["restricted_domain"] = o.RestrictedDomain
	}
	toSerialize["trigger_login_automatically"] = o.TriggerLoginAutomatically
	return toSerialize, nil
}

func (o *GoogleSAML) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config_type",
		"google_client_id",
		"google_client_secret",
		"disable_email_password_login",
		"idp_metadata_xml",
		"saml_first_name_attribute",
		"saml_last_name_attribute",
		"saml_sync_group_claims",
		"jit_enabled",
		"trigger_login_automatically",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoogleSAML := _GoogleSAML{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoogleSAML)

	if err != nil {
		return err
	}

	*o = GoogleSAML(varGoogleSAML)

	return err
}

type NullableGoogleSAML struct {
	value *GoogleSAML
	isSet bool
}

func (v NullableGoogleSAML) Get() *GoogleSAML {
	return v.value
}

func (v *NullableGoogleSAML) Set(val *GoogleSAML) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleSAML) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleSAML) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleSAML(val *GoogleSAML) *NullableGoogleSAML {
	return &NullableGoogleSAML{value: val, isSet: true}
}

func (v NullableGoogleSAML) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleSAML) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


