/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// PermissionsGrantPostRequestObject - struct for PermissionsGrantPostRequestObject
type PermissionsGrantPostRequestObject struct {
	PermissionsGrantPostRequestObjectOneOf *PermissionsGrantPostRequestObjectOneOf
	PermissionsGrantPostRequestObjectOneOf1 *PermissionsGrantPostRequestObjectOneOf1
	PermissionsGrantPostRequestObjectOneOf2 *PermissionsGrantPostRequestObjectOneOf2
	PermissionsGrantPostRequestObjectOneOf3 *PermissionsGrantPostRequestObjectOneOf3
}

// PermissionsGrantPostRequestObjectOneOfAsPermissionsGrantPostRequestObject is a convenience function that returns PermissionsGrantPostRequestObjectOneOf wrapped in PermissionsGrantPostRequestObject
func PermissionsGrantPostRequestObjectOneOfAsPermissionsGrantPostRequestObject(v *PermissionsGrantPostRequestObjectOneOf) PermissionsGrantPostRequestObject {
	return PermissionsGrantPostRequestObject{
		PermissionsGrantPostRequestObjectOneOf: v,
	}
}

// PermissionsGrantPostRequestObjectOneOf1AsPermissionsGrantPostRequestObject is a convenience function that returns PermissionsGrantPostRequestObjectOneOf1 wrapped in PermissionsGrantPostRequestObject
func PermissionsGrantPostRequestObjectOneOf1AsPermissionsGrantPostRequestObject(v *PermissionsGrantPostRequestObjectOneOf1) PermissionsGrantPostRequestObject {
	return PermissionsGrantPostRequestObject{
		PermissionsGrantPostRequestObjectOneOf1: v,
	}
}

// PermissionsGrantPostRequestObjectOneOf2AsPermissionsGrantPostRequestObject is a convenience function that returns PermissionsGrantPostRequestObjectOneOf2 wrapped in PermissionsGrantPostRequestObject
func PermissionsGrantPostRequestObjectOneOf2AsPermissionsGrantPostRequestObject(v *PermissionsGrantPostRequestObjectOneOf2) PermissionsGrantPostRequestObject {
	return PermissionsGrantPostRequestObject{
		PermissionsGrantPostRequestObjectOneOf2: v,
	}
}

// PermissionsGrantPostRequestObjectOneOf3AsPermissionsGrantPostRequestObject is a convenience function that returns PermissionsGrantPostRequestObjectOneOf3 wrapped in PermissionsGrantPostRequestObject
func PermissionsGrantPostRequestObjectOneOf3AsPermissionsGrantPostRequestObject(v *PermissionsGrantPostRequestObjectOneOf3) PermissionsGrantPostRequestObject {
	return PermissionsGrantPostRequestObject{
		PermissionsGrantPostRequestObjectOneOf3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PermissionsGrantPostRequestObject) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PermissionsGrantPostRequestObjectOneOf
	err = newStrictDecoder(data).Decode(&dst.PermissionsGrantPostRequestObjectOneOf)
	if err == nil {
		jsonPermissionsGrantPostRequestObjectOneOf, _ := json.Marshal(dst.PermissionsGrantPostRequestObjectOneOf)
		if string(jsonPermissionsGrantPostRequestObjectOneOf) == "{}" { // empty struct
			dst.PermissionsGrantPostRequestObjectOneOf = nil
		} else {
			match++
		}
	} else {
		dst.PermissionsGrantPostRequestObjectOneOf = nil
	}

	// try to unmarshal data into PermissionsGrantPostRequestObjectOneOf1
	err = newStrictDecoder(data).Decode(&dst.PermissionsGrantPostRequestObjectOneOf1)
	if err == nil {
		jsonPermissionsGrantPostRequestObjectOneOf1, _ := json.Marshal(dst.PermissionsGrantPostRequestObjectOneOf1)
		if string(jsonPermissionsGrantPostRequestObjectOneOf1) == "{}" { // empty struct
			dst.PermissionsGrantPostRequestObjectOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.PermissionsGrantPostRequestObjectOneOf1 = nil
	}

	// try to unmarshal data into PermissionsGrantPostRequestObjectOneOf2
	err = newStrictDecoder(data).Decode(&dst.PermissionsGrantPostRequestObjectOneOf2)
	if err == nil {
		jsonPermissionsGrantPostRequestObjectOneOf2, _ := json.Marshal(dst.PermissionsGrantPostRequestObjectOneOf2)
		if string(jsonPermissionsGrantPostRequestObjectOneOf2) == "{}" { // empty struct
			dst.PermissionsGrantPostRequestObjectOneOf2 = nil
		} else {
			match++
		}
	} else {
		dst.PermissionsGrantPostRequestObjectOneOf2 = nil
	}

	// try to unmarshal data into PermissionsGrantPostRequestObjectOneOf3
	err = newStrictDecoder(data).Decode(&dst.PermissionsGrantPostRequestObjectOneOf3)
	if err == nil {
		jsonPermissionsGrantPostRequestObjectOneOf3, _ := json.Marshal(dst.PermissionsGrantPostRequestObjectOneOf3)
		if string(jsonPermissionsGrantPostRequestObjectOneOf3) == "{}" { // empty struct
			dst.PermissionsGrantPostRequestObjectOneOf3 = nil
		} else {
			match++
		}
	} else {
		dst.PermissionsGrantPostRequestObjectOneOf3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PermissionsGrantPostRequestObjectOneOf = nil
		dst.PermissionsGrantPostRequestObjectOneOf1 = nil
		dst.PermissionsGrantPostRequestObjectOneOf2 = nil
		dst.PermissionsGrantPostRequestObjectOneOf3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PermissionsGrantPostRequestObject)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PermissionsGrantPostRequestObject)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PermissionsGrantPostRequestObject) MarshalJSON() ([]byte, error) {
	if src.PermissionsGrantPostRequestObjectOneOf != nil {
		return json.Marshal(&src.PermissionsGrantPostRequestObjectOneOf)
	}

	if src.PermissionsGrantPostRequestObjectOneOf1 != nil {
		return json.Marshal(&src.PermissionsGrantPostRequestObjectOneOf1)
	}

	if src.PermissionsGrantPostRequestObjectOneOf2 != nil {
		return json.Marshal(&src.PermissionsGrantPostRequestObjectOneOf2)
	}

	if src.PermissionsGrantPostRequestObjectOneOf3 != nil {
		return json.Marshal(&src.PermissionsGrantPostRequestObjectOneOf3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PermissionsGrantPostRequestObject) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PermissionsGrantPostRequestObjectOneOf != nil {
		return obj.PermissionsGrantPostRequestObjectOneOf
	}

	if obj.PermissionsGrantPostRequestObjectOneOf1 != nil {
		return obj.PermissionsGrantPostRequestObjectOneOf1
	}

	if obj.PermissionsGrantPostRequestObjectOneOf2 != nil {
		return obj.PermissionsGrantPostRequestObjectOneOf2
	}

	if obj.PermissionsGrantPostRequestObjectOneOf3 != nil {
		return obj.PermissionsGrantPostRequestObjectOneOf3
	}

	// all schemas are nil
	return nil
}

type NullablePermissionsGrantPostRequestObject struct {
	value *PermissionsGrantPostRequestObject
	isSet bool
}

func (v NullablePermissionsGrantPostRequestObject) Get() *PermissionsGrantPostRequestObject {
	return v.value
}

func (v *NullablePermissionsGrantPostRequestObject) Set(val *PermissionsGrantPostRequestObject) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionsGrantPostRequestObject) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionsGrantPostRequestObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionsGrantPostRequestObject(val *PermissionsGrantPostRequestObject) *NullablePermissionsGrantPostRequestObject {
	return &NullablePermissionsGrantPostRequestObject{value: val, isSet: true}
}

func (v NullablePermissionsGrantPostRequestObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionsGrantPostRequestObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


