/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AzureOpenAIOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureOpenAIOptions{}

// AzureOpenAIOptions struct for AzureOpenAIOptions
type AzureOpenAIOptions struct {
	// Always 'byok' (bring your own key) — this provider requires you to supply credentials. Defaults to 'byok' and may be omitted.
	KeySource string `json:"key_source"`
	BaseUrl string `json:"base_url"`
	ApiKey string `json:"api_key"`
	DeploymentNames []string `json:"deployment_names"`
	ApiVersion *string `json:"api_version,omitempty"`
	CustomHeaders [][]string `json:"custom_headers,omitempty"`
}

type _AzureOpenAIOptions AzureOpenAIOptions

// NewAzureOpenAIOptions instantiates a new AzureOpenAIOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureOpenAIOptions(keySource string, baseUrl string, apiKey string, deploymentNames []string) *AzureOpenAIOptions {
	this := AzureOpenAIOptions{}
	this.KeySource = keySource
	this.BaseUrl = baseUrl
	this.ApiKey = apiKey
	this.DeploymentNames = deploymentNames
	return &this
}

// NewAzureOpenAIOptionsWithDefaults instantiates a new AzureOpenAIOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureOpenAIOptionsWithDefaults() *AzureOpenAIOptions {
	this := AzureOpenAIOptions{}
	var keySource string = "byok"
	this.KeySource = keySource
	return &this
}

// GetKeySource returns the KeySource field value
func (o *AzureOpenAIOptions) GetKeySource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeySource
}

// GetKeySourceOk returns a tuple with the KeySource field value
// and a boolean to check if the value has been set.
func (o *AzureOpenAIOptions) GetKeySourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeySource, true
}

// SetKeySource sets field value
func (o *AzureOpenAIOptions) SetKeySource(v string) {
	o.KeySource = v
}

// GetBaseUrl returns the BaseUrl field value
func (o *AzureOpenAIOptions) GetBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseUrl
}

// GetBaseUrlOk returns a tuple with the BaseUrl field value
// and a boolean to check if the value has been set.
func (o *AzureOpenAIOptions) GetBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseUrl, true
}

// SetBaseUrl sets field value
func (o *AzureOpenAIOptions) SetBaseUrl(v string) {
	o.BaseUrl = v
}

// GetApiKey returns the ApiKey field value
func (o *AzureOpenAIOptions) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *AzureOpenAIOptions) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *AzureOpenAIOptions) SetApiKey(v string) {
	o.ApiKey = v
}

// GetDeploymentNames returns the DeploymentNames field value
func (o *AzureOpenAIOptions) GetDeploymentNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DeploymentNames
}

// GetDeploymentNamesOk returns a tuple with the DeploymentNames field value
// and a boolean to check if the value has been set.
func (o *AzureOpenAIOptions) GetDeploymentNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeploymentNames, true
}

// SetDeploymentNames sets field value
func (o *AzureOpenAIOptions) SetDeploymentNames(v []string) {
	o.DeploymentNames = v
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *AzureOpenAIOptions) GetApiVersion() string {
	if o == nil || IsNil(o.ApiVersion) {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureOpenAIOptions) GetApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *AzureOpenAIOptions) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *AzureOpenAIOptions) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetCustomHeaders returns the CustomHeaders field value if set, zero value otherwise.
func (o *AzureOpenAIOptions) GetCustomHeaders() [][]string {
	if o == nil || IsNil(o.CustomHeaders) {
		var ret [][]string
		return ret
	}
	return o.CustomHeaders
}

// GetCustomHeadersOk returns a tuple with the CustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AzureOpenAIOptions) GetCustomHeadersOk() ([][]string, bool) {
	if o == nil || IsNil(o.CustomHeaders) {
		return nil, false
	}
	return o.CustomHeaders, true
}

// HasCustomHeaders returns a boolean if a field has been set.
func (o *AzureOpenAIOptions) HasCustomHeaders() bool {
	if o != nil && !IsNil(o.CustomHeaders) {
		return true
	}

	return false
}

// SetCustomHeaders gets a reference to the given [][]string and assigns it to the CustomHeaders field.
func (o *AzureOpenAIOptions) SetCustomHeaders(v [][]string) {
	o.CustomHeaders = v
}

func (o AzureOpenAIOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureOpenAIOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key_source"] = o.KeySource
	toSerialize["base_url"] = o.BaseUrl
	toSerialize["api_key"] = o.ApiKey
	toSerialize["deployment_names"] = o.DeploymentNames
	if !IsNil(o.ApiVersion) {
		toSerialize["api_version"] = o.ApiVersion
	}
	if !IsNil(o.CustomHeaders) {
		toSerialize["custom_headers"] = o.CustomHeaders
	}
	return toSerialize, nil
}

func (o *AzureOpenAIOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key_source",
		"base_url",
		"api_key",
		"deployment_names",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureOpenAIOptions := _AzureOpenAIOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureOpenAIOptions)

	if err != nil {
		return err
	}

	*o = AzureOpenAIOptions(varAzureOpenAIOptions)

	return err
}

type NullableAzureOpenAIOptions struct {
	value *AzureOpenAIOptions
	isSet bool
}

func (v NullableAzureOpenAIOptions) Get() *AzureOpenAIOptions {
	return v.value
}

func (v *NullableAzureOpenAIOptions) Set(val *AzureOpenAIOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureOpenAIOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureOpenAIOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureOpenAIOptions(val *AzureOpenAIOptions) *NullableAzureOpenAIOptions {
	return &NullableAzureOpenAIOptions{value: val, isSet: true}
}

func (v NullableAzureOpenAIOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureOpenAIOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


