/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PermissionsAccessListObjectTypeObjectIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionsAccessListObjectTypeObjectIdGet200Response{}

// PermissionsAccessListObjectTypeObjectIdGet200Response struct for PermissionsAccessListObjectTypeObjectIdGet200Response
type PermissionsAccessListObjectTypeObjectIdGet200Response struct {
	// API request succeeded
	Success bool `json:"success"`
	Data PermissionsAccessListObjectTypeObjectIdGet200ResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _PermissionsAccessListObjectTypeObjectIdGet200Response PermissionsAccessListObjectTypeObjectIdGet200Response

// NewPermissionsAccessListObjectTypeObjectIdGet200Response instantiates a new PermissionsAccessListObjectTypeObjectIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionsAccessListObjectTypeObjectIdGet200Response(success bool, data PermissionsAccessListObjectTypeObjectIdGet200ResponseData) *PermissionsAccessListObjectTypeObjectIdGet200Response {
	this := PermissionsAccessListObjectTypeObjectIdGet200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewPermissionsAccessListObjectTypeObjectIdGet200ResponseWithDefaults instantiates a new PermissionsAccessListObjectTypeObjectIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsAccessListObjectTypeObjectIdGet200ResponseWithDefaults() *PermissionsAccessListObjectTypeObjectIdGet200Response {
	this := PermissionsAccessListObjectTypeObjectIdGet200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) GetData() PermissionsAccessListObjectTypeObjectIdGet200ResponseData {
	if o == nil {
		var ret PermissionsAccessListObjectTypeObjectIdGet200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) GetDataOk() (*PermissionsAccessListObjectTypeObjectIdGet200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) SetData(v PermissionsAccessListObjectTypeObjectIdGet200ResponseData) {
	o.Data = v
}

func (o PermissionsAccessListObjectTypeObjectIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionsAccessListObjectTypeObjectIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PermissionsAccessListObjectTypeObjectIdGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionsAccessListObjectTypeObjectIdGet200Response := _PermissionsAccessListObjectTypeObjectIdGet200Response{}

	err = json.Unmarshal(data, &varPermissionsAccessListObjectTypeObjectIdGet200Response)

	if err != nil {
		return err
	}

	*o = PermissionsAccessListObjectTypeObjectIdGet200Response(varPermissionsAccessListObjectTypeObjectIdGet200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePermissionsAccessListObjectTypeObjectIdGet200Response struct {
	value *PermissionsAccessListObjectTypeObjectIdGet200Response
	isSet bool
}

func (v NullablePermissionsAccessListObjectTypeObjectIdGet200Response) Get() *PermissionsAccessListObjectTypeObjectIdGet200Response {
	return v.value
}

func (v *NullablePermissionsAccessListObjectTypeObjectIdGet200Response) Set(val *PermissionsAccessListObjectTypeObjectIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionsAccessListObjectTypeObjectIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionsAccessListObjectTypeObjectIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionsAccessListObjectTypeObjectIdGet200Response(val *PermissionsAccessListObjectTypeObjectIdGet200Response) *NullablePermissionsAccessListObjectTypeObjectIdGet200Response {
	return &NullablePermissionsAccessListObjectTypeObjectIdGet200Response{value: val, isSet: true}
}

func (v NullablePermissionsAccessListObjectTypeObjectIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionsAccessListObjectTypeObjectIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


