/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomComponentLibrariesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomComponentLibrariesPost200Response{}

// CustomComponentLibrariesPost200Response The newly created Custom Component Library.
type CustomComponentLibrariesPost200Response struct {
	// Whether the API request was successful.
	Success bool `json:"success"`
	Data CustomComponentLibrariesLibraryIdGet200ResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _CustomComponentLibrariesPost200Response CustomComponentLibrariesPost200Response

// NewCustomComponentLibrariesPost200Response instantiates a new CustomComponentLibrariesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomComponentLibrariesPost200Response(success bool, data CustomComponentLibrariesLibraryIdGet200ResponseData) *CustomComponentLibrariesPost200Response {
	this := CustomComponentLibrariesPost200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewCustomComponentLibrariesPost200ResponseWithDefaults instantiates a new CustomComponentLibrariesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomComponentLibrariesPost200ResponseWithDefaults() *CustomComponentLibrariesPost200Response {
	this := CustomComponentLibrariesPost200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *CustomComponentLibrariesPost200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *CustomComponentLibrariesPost200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *CustomComponentLibrariesPost200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *CustomComponentLibrariesPost200Response) GetData() CustomComponentLibrariesLibraryIdGet200ResponseData {
	if o == nil {
		var ret CustomComponentLibrariesLibraryIdGet200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CustomComponentLibrariesPost200Response) GetDataOk() (*CustomComponentLibrariesLibraryIdGet200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CustomComponentLibrariesPost200Response) SetData(v CustomComponentLibrariesLibraryIdGet200ResponseData) {
	o.Data = v
}

func (o CustomComponentLibrariesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomComponentLibrariesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomComponentLibrariesPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomComponentLibrariesPost200Response := _CustomComponentLibrariesPost200Response{}

	err = json.Unmarshal(data, &varCustomComponentLibrariesPost200Response)

	if err != nil {
		return err
	}

	*o = CustomComponentLibrariesPost200Response(varCustomComponentLibrariesPost200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomComponentLibrariesPost200Response struct {
	value *CustomComponentLibrariesPost200Response
	isSet bool
}

func (v NullableCustomComponentLibrariesPost200Response) Get() *CustomComponentLibrariesPost200Response {
	return v.value
}

func (v *NullableCustomComponentLibrariesPost200Response) Set(val *CustomComponentLibrariesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomComponentLibrariesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomComponentLibrariesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomComponentLibrariesPost200Response(val *CustomComponentLibrariesPost200Response) *NullableCustomComponentLibrariesPost200Response {
	return &NullableCustomComponentLibrariesPost200Response{value: val, isSet: true}
}

func (v NullableCustomComponentLibrariesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomComponentLibrariesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


