/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// RestAPIOptionsAuthenticationOptions Note that custom auth is not yet supported.
type RestAPIOptionsAuthenticationOptions struct {
	RestAPIOptionsAuthenticationOptionsAnyOf *RestAPIOptionsAuthenticationOptionsAnyOf
	RestAPIOptionsAuthenticationOptionsAnyOf1 *RestAPIOptionsAuthenticationOptionsAnyOf1
	RestAPIOptionsAuthenticationOptionsAnyOf10 *RestAPIOptionsAuthenticationOptionsAnyOf10
	RestAPIOptionsAuthenticationOptionsAnyOf2 *RestAPIOptionsAuthenticationOptionsAnyOf2
	RestAPIOptionsAuthenticationOptionsAnyOf3 *RestAPIOptionsAuthenticationOptionsAnyOf3
	RestAPIOptionsAuthenticationOptionsAnyOf4 *RestAPIOptionsAuthenticationOptionsAnyOf4
	RestAPIOptionsAuthenticationOptionsAnyOf5 *RestAPIOptionsAuthenticationOptionsAnyOf5
	RestAPIOptionsAuthenticationOptionsAnyOf6 *RestAPIOptionsAuthenticationOptionsAnyOf6
	RestAPIOptionsAuthenticationOptionsAnyOf7 *RestAPIOptionsAuthenticationOptionsAnyOf7
	RestAPIOptionsAuthenticationOptionsAnyOf8 *RestAPIOptionsAuthenticationOptionsAnyOf8
	RestAPIOptionsAuthenticationOptionsAnyOf9 *RestAPIOptionsAuthenticationOptionsAnyOf9
	SnowflakeOptionsAuthenticationOptionsAnyOf *SnowflakeOptionsAuthenticationOptionsAnyOf
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RestAPIOptionsAuthenticationOptions) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf1
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf1);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf1, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf1)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf1) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf1 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf1, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf1 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf10
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf10);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf10, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf10)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf10) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf10 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf10, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf10 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf2
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf2);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf2, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf2)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf2) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf2 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf2, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf2 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf3
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf3);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf3, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf3)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf3) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf3 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf3, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf3 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf4
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf4);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf4, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf4)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf4) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf4 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf4, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf4 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf5
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf5);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf5, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf5)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf5) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf5 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf5, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf5 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf6
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf6);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf6, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf6)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf6) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf6 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf6, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf6 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf7
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf7);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf7, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf7)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf7) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf7 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf7, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf7 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf8
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf8);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf8, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf8)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf8) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf8 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf8, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf8 = nil
	}

	// try to unmarshal JSON data into RestAPIOptionsAuthenticationOptionsAnyOf9
	err = json.Unmarshal(data, &dst.RestAPIOptionsAuthenticationOptionsAnyOf9);
	if err == nil {
		jsonRestAPIOptionsAuthenticationOptionsAnyOf9, _ := json.Marshal(dst.RestAPIOptionsAuthenticationOptionsAnyOf9)
		if string(jsonRestAPIOptionsAuthenticationOptionsAnyOf9) == "{}" { // empty struct
			dst.RestAPIOptionsAuthenticationOptionsAnyOf9 = nil
		} else {
			return nil // data stored in dst.RestAPIOptionsAuthenticationOptionsAnyOf9, return on the first match
		}
	} else {
		dst.RestAPIOptionsAuthenticationOptionsAnyOf9 = nil
	}

	// try to unmarshal JSON data into SnowflakeOptionsAuthenticationOptionsAnyOf
	err = json.Unmarshal(data, &dst.SnowflakeOptionsAuthenticationOptionsAnyOf);
	if err == nil {
		jsonSnowflakeOptionsAuthenticationOptionsAnyOf, _ := json.Marshal(dst.SnowflakeOptionsAuthenticationOptionsAnyOf)
		if string(jsonSnowflakeOptionsAuthenticationOptionsAnyOf) == "{}" { // empty struct
			dst.SnowflakeOptionsAuthenticationOptionsAnyOf = nil
		} else {
			return nil // data stored in dst.SnowflakeOptionsAuthenticationOptionsAnyOf, return on the first match
		}
	} else {
		dst.SnowflakeOptionsAuthenticationOptionsAnyOf = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RestAPIOptionsAuthenticationOptions)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RestAPIOptionsAuthenticationOptions) MarshalJSON() ([]byte, error) {
	if src.RestAPIOptionsAuthenticationOptionsAnyOf != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf1 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf1)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf10 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf10)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf2 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf2)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf3 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf3)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf4 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf4)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf5 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf5)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf6 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf6)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf7 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf7)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf8 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf8)
	}

	if src.RestAPIOptionsAuthenticationOptionsAnyOf9 != nil {
		return json.Marshal(src.RestAPIOptionsAuthenticationOptionsAnyOf9)
	}

	if src.SnowflakeOptionsAuthenticationOptionsAnyOf != nil {
		return json.Marshal(src.SnowflakeOptionsAuthenticationOptionsAnyOf)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableRestAPIOptionsAuthenticationOptions struct {
	value *RestAPIOptionsAuthenticationOptions
	isSet bool
}

func (v NullableRestAPIOptionsAuthenticationOptions) Get() *RestAPIOptionsAuthenticationOptions {
	return v.value
}

func (v *NullableRestAPIOptionsAuthenticationOptions) Set(val *RestAPIOptionsAuthenticationOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableRestAPIOptionsAuthenticationOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableRestAPIOptionsAuthenticationOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestAPIOptionsAuthenticationOptions(val *RestAPIOptionsAuthenticationOptions) *NullableRestAPIOptionsAuthenticationOptions {
	return &NullableRestAPIOptionsAuthenticationOptions{value: val, isSet: true}
}

func (v NullableRestAPIOptionsAuthenticationOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestAPIOptionsAuthenticationOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


