/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1{}

// SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 struct for SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1
type SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 struct {
	Type string `json:"type"`
	// The GitHub project access token to authenticate to the GitHub API. 
	PersonalAccessToken string `json:"personal_access_token"`
	// The domain used to access your self-hosted GitHub instance.
	Url *string `json:"url,omitempty"`
	// The REST API route for your self-hosted GitHub instance. Defaults to https://[hostname]/api/v3.
	EnterpriseApiUrl *string `json:"enterprise_api_url,omitempty"`
}

type _SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1

// NewSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 instantiates a new SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1(type_ string, personalAccessToken string) *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 {
	this := SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1{}
	this.Type = type_
	this.PersonalAccessToken = personalAccessToken
	return &this
}

// NewSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1WithDefaults instantiates a new SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1WithDefaults() *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 {
	this := SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1{}
	return &this
}

// GetType returns the Type field value
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) SetType(v string) {
	o.Type = v
}

// GetPersonalAccessToken returns the PersonalAccessToken field value
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetPersonalAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PersonalAccessToken
}

// GetPersonalAccessTokenOk returns a tuple with the PersonalAccessToken field value
// and a boolean to check if the value has been set.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetPersonalAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PersonalAccessToken, true
}

// SetPersonalAccessToken sets field value
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) SetPersonalAccessToken(v string) {
	o.PersonalAccessToken = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) SetUrl(v string) {
	o.Url = &v
}

// GetEnterpriseApiUrl returns the EnterpriseApiUrl field value if set, zero value otherwise.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetEnterpriseApiUrl() string {
	if o == nil || IsNil(o.EnterpriseApiUrl) {
		var ret string
		return ret
	}
	return *o.EnterpriseApiUrl
}

// GetEnterpriseApiUrlOk returns a tuple with the EnterpriseApiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) GetEnterpriseApiUrlOk() (*string, bool) {
	if o == nil || IsNil(o.EnterpriseApiUrl) {
		return nil, false
	}
	return o.EnterpriseApiUrl, true
}

// HasEnterpriseApiUrl returns a boolean if a field has been set.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) HasEnterpriseApiUrl() bool {
	if o != nil && !IsNil(o.EnterpriseApiUrl) {
		return true
	}

	return false
}

// SetEnterpriseApiUrl gets a reference to the given string and assigns it to the EnterpriseApiUrl field.
func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) SetEnterpriseApiUrl(v string) {
	o.EnterpriseApiUrl = &v
}

func (o SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["personal_access_token"] = o.PersonalAccessToken
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.EnterpriseApiUrl) {
		toSerialize["enterprise_api_url"] = o.EnterpriseApiUrl
	}
	return toSerialize, nil
}

func (o *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"personal_access_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 := _SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1)

	if err != nil {
		return err
	}

	*o = SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1(varSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1)

	return err
}

type NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 struct {
	value *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1
	isSet bool
}

func (v NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) Get() *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 {
	return v.value
}

func (v *NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) Set(val *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1(val *SourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) *NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1 {
	return &NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1{value: val, isSet: true}
}

func (v NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlConfigGet200ResponseDataAnyOfConfigAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


