/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersUserIdUserAttributesAttributeNameDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersUserIdUserAttributesAttributeNameDelete200Response{}

// UsersUserIdUserAttributesAttributeNameDelete200Response struct for UsersUserIdUserAttributesAttributeNameDelete200Response
type UsersUserIdUserAttributesAttributeNameDelete200Response struct {
	// API request succeeded
	Success bool `json:"success"`
	Data UsersUserIdUserAttributesAttributeNameDelete200ResponseData `json:"data"`
}

type _UsersUserIdUserAttributesAttributeNameDelete200Response UsersUserIdUserAttributesAttributeNameDelete200Response

// NewUsersUserIdUserAttributesAttributeNameDelete200Response instantiates a new UsersUserIdUserAttributesAttributeNameDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersUserIdUserAttributesAttributeNameDelete200Response(success bool, data UsersUserIdUserAttributesAttributeNameDelete200ResponseData) *UsersUserIdUserAttributesAttributeNameDelete200Response {
	this := UsersUserIdUserAttributesAttributeNameDelete200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewUsersUserIdUserAttributesAttributeNameDelete200ResponseWithDefaults instantiates a new UsersUserIdUserAttributesAttributeNameDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersUserIdUserAttributesAttributeNameDelete200ResponseWithDefaults() *UsersUserIdUserAttributesAttributeNameDelete200Response {
	this := UsersUserIdUserAttributesAttributeNameDelete200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) GetData() UsersUserIdUserAttributesAttributeNameDelete200ResponseData {
	if o == nil {
		var ret UsersUserIdUserAttributesAttributeNameDelete200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) GetDataOk() (*UsersUserIdUserAttributesAttributeNameDelete200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) SetData(v UsersUserIdUserAttributesAttributeNameDelete200ResponseData) {
	o.Data = v
}

func (o UsersUserIdUserAttributesAttributeNameDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersUserIdUserAttributesAttributeNameDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UsersUserIdUserAttributesAttributeNameDelete200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersUserIdUserAttributesAttributeNameDelete200Response := _UsersUserIdUserAttributesAttributeNameDelete200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersUserIdUserAttributesAttributeNameDelete200Response)

	if err != nil {
		return err
	}

	*o = UsersUserIdUserAttributesAttributeNameDelete200Response(varUsersUserIdUserAttributesAttributeNameDelete200Response)

	return err
}

type NullableUsersUserIdUserAttributesAttributeNameDelete200Response struct {
	value *UsersUserIdUserAttributesAttributeNameDelete200Response
	isSet bool
}

func (v NullableUsersUserIdUserAttributesAttributeNameDelete200Response) Get() *UsersUserIdUserAttributesAttributeNameDelete200Response {
	return v.value
}

func (v *NullableUsersUserIdUserAttributesAttributeNameDelete200Response) Set(val *UsersUserIdUserAttributesAttributeNameDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersUserIdUserAttributesAttributeNameDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersUserIdUserAttributesAttributeNameDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersUserIdUserAttributesAttributeNameDelete200Response(val *UsersUserIdUserAttributesAttributeNameDelete200Response) *NullableUsersUserIdUserAttributesAttributeNameDelete200Response {
	return &NullableUsersUserIdUserAttributesAttributeNameDelete200Response{value: val, isSet: true}
}

func (v NullableUsersUserIdUserAttributesAttributeNameDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersUserIdUserAttributesAttributeNameDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


