/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SourceControlBranchesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceControlBranchesPost200Response{}

// SourceControlBranchesPost200Response struct for SourceControlBranchesPost200Response
type SourceControlBranchesPost200Response struct {
	// Whether the API request was successful.
	Success bool `json:"success"`
	Data SourceControlBranchesPost200ResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SourceControlBranchesPost200Response SourceControlBranchesPost200Response

// NewSourceControlBranchesPost200Response instantiates a new SourceControlBranchesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceControlBranchesPost200Response(success bool, data SourceControlBranchesPost200ResponseData) *SourceControlBranchesPost200Response {
	this := SourceControlBranchesPost200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewSourceControlBranchesPost200ResponseWithDefaults instantiates a new SourceControlBranchesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceControlBranchesPost200ResponseWithDefaults() *SourceControlBranchesPost200Response {
	this := SourceControlBranchesPost200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *SourceControlBranchesPost200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesPost200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *SourceControlBranchesPost200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *SourceControlBranchesPost200Response) GetData() SourceControlBranchesPost200ResponseData {
	if o == nil {
		var ret SourceControlBranchesPost200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SourceControlBranchesPost200Response) GetDataOk() (*SourceControlBranchesPost200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SourceControlBranchesPost200Response) SetData(v SourceControlBranchesPost200ResponseData) {
	o.Data = v
}

func (o SourceControlBranchesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceControlBranchesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SourceControlBranchesPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceControlBranchesPost200Response := _SourceControlBranchesPost200Response{}

	err = json.Unmarshal(data, &varSourceControlBranchesPost200Response)

	if err != nil {
		return err
	}

	*o = SourceControlBranchesPost200Response(varSourceControlBranchesPost200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSourceControlBranchesPost200Response struct {
	value *SourceControlBranchesPost200Response
	isSet bool
}

func (v NullableSourceControlBranchesPost200Response) Get() *SourceControlBranchesPost200Response {
	return v.value
}

func (v *NullableSourceControlBranchesPost200Response) Set(val *SourceControlBranchesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlBranchesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlBranchesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlBranchesPost200Response(val *SourceControlBranchesPost200Response) *NullableSourceControlBranchesPost200Response {
	return &NullableSourceControlBranchesPost200Response{value: val, isSet: true}
}

func (v NullableSourceControlBranchesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlBranchesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


