/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UsageAnalyticsOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageAnalyticsOrganization{}

// UsageAnalyticsOrganization An organization in the context of usage analytics
type UsageAnalyticsOrganization struct {
	// The id of the organization
	OrgId string `json:"org_id"`
	// The host of the organization
	Host string `json:"host"`
	LastActive time.Time `json:"last_active"`
}

type _UsageAnalyticsOrganization UsageAnalyticsOrganization

// NewUsageAnalyticsOrganization instantiates a new UsageAnalyticsOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageAnalyticsOrganization(orgId string, host string, lastActive time.Time) *UsageAnalyticsOrganization {
	this := UsageAnalyticsOrganization{}
	this.OrgId = orgId
	this.Host = host
	this.LastActive = lastActive
	return &this
}

// NewUsageAnalyticsOrganizationWithDefaults instantiates a new UsageAnalyticsOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageAnalyticsOrganizationWithDefaults() *UsageAnalyticsOrganization {
	this := UsageAnalyticsOrganization{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *UsageAnalyticsOrganization) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *UsageAnalyticsOrganization) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *UsageAnalyticsOrganization) SetOrgId(v string) {
	o.OrgId = v
}

// GetHost returns the Host field value
func (o *UsageAnalyticsOrganization) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *UsageAnalyticsOrganization) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *UsageAnalyticsOrganization) SetHost(v string) {
	o.Host = v
}

// GetLastActive returns the LastActive field value
func (o *UsageAnalyticsOrganization) GetLastActive() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastActive
}

// GetLastActiveOk returns a tuple with the LastActive field value
// and a boolean to check if the value has been set.
func (o *UsageAnalyticsOrganization) GetLastActiveOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastActive, true
}

// SetLastActive sets field value
func (o *UsageAnalyticsOrganization) SetLastActive(v time.Time) {
	o.LastActive = v
}

func (o UsageAnalyticsOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageAnalyticsOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["org_id"] = o.OrgId
	toSerialize["host"] = o.Host
	toSerialize["last_active"] = o.LastActive
	return toSerialize, nil
}

func (o *UsageAnalyticsOrganization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_id",
		"host",
		"last_active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageAnalyticsOrganization := _UsageAnalyticsOrganization{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageAnalyticsOrganization)

	if err != nil {
		return err
	}

	*o = UsageAnalyticsOrganization(varUsageAnalyticsOrganization)

	return err
}

type NullableUsageAnalyticsOrganization struct {
	value *UsageAnalyticsOrganization
	isSet bool
}

func (v NullableUsageAnalyticsOrganization) Get() *UsageAnalyticsOrganization {
	return v.value
}

func (v *NullableUsageAnalyticsOrganization) Set(val *UsageAnalyticsOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageAnalyticsOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageAnalyticsOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageAnalyticsOrganization(val *UsageAnalyticsOrganization) *NullableUsageAnalyticsOrganization {
	return &NullableUsageAnalyticsOrganization{value: val, isSet: true}
}

func (v NullableUsageAnalyticsOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageAnalyticsOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


