/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupsGroupIdPutRequestMembersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupsGroupIdPutRequestMembersInner{}

// GroupsGroupIdPutRequestMembersInner struct for GroupsGroupIdPutRequestMembersInner
type GroupsGroupIdPutRequestMembersInner struct {
	// The unique identifier for the user.
	Id string `json:"id"`
	// Whether the user is a group admin.
	IsGroupAdmin bool `json:"is_group_admin"`
	AdditionalProperties map[string]interface{}
}

type _GroupsGroupIdPutRequestMembersInner GroupsGroupIdPutRequestMembersInner

// NewGroupsGroupIdPutRequestMembersInner instantiates a new GroupsGroupIdPutRequestMembersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupsGroupIdPutRequestMembersInner(id string, isGroupAdmin bool) *GroupsGroupIdPutRequestMembersInner {
	this := GroupsGroupIdPutRequestMembersInner{}
	this.Id = id
	this.IsGroupAdmin = isGroupAdmin
	return &this
}

// NewGroupsGroupIdPutRequestMembersInnerWithDefaults instantiates a new GroupsGroupIdPutRequestMembersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupsGroupIdPutRequestMembersInnerWithDefaults() *GroupsGroupIdPutRequestMembersInner {
	this := GroupsGroupIdPutRequestMembersInner{}
	var isGroupAdmin bool = false
	this.IsGroupAdmin = isGroupAdmin
	return &this
}

// GetId returns the Id field value
func (o *GroupsGroupIdPutRequestMembersInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GroupsGroupIdPutRequestMembersInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GroupsGroupIdPutRequestMembersInner) SetId(v string) {
	o.Id = v
}

// GetIsGroupAdmin returns the IsGroupAdmin field value
func (o *GroupsGroupIdPutRequestMembersInner) GetIsGroupAdmin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsGroupAdmin
}

// GetIsGroupAdminOk returns a tuple with the IsGroupAdmin field value
// and a boolean to check if the value has been set.
func (o *GroupsGroupIdPutRequestMembersInner) GetIsGroupAdminOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsGroupAdmin, true
}

// SetIsGroupAdmin sets field value
func (o *GroupsGroupIdPutRequestMembersInner) SetIsGroupAdmin(v bool) {
	o.IsGroupAdmin = v
}

func (o GroupsGroupIdPutRequestMembersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupsGroupIdPutRequestMembersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["is_group_admin"] = o.IsGroupAdmin

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupsGroupIdPutRequestMembersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"is_group_admin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupsGroupIdPutRequestMembersInner := _GroupsGroupIdPutRequestMembersInner{}

	err = json.Unmarshal(data, &varGroupsGroupIdPutRequestMembersInner)

	if err != nil {
		return err
	}

	*o = GroupsGroupIdPutRequestMembersInner(varGroupsGroupIdPutRequestMembersInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "is_group_admin")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupsGroupIdPutRequestMembersInner struct {
	value *GroupsGroupIdPutRequestMembersInner
	isSet bool
}

func (v NullableGroupsGroupIdPutRequestMembersInner) Get() *GroupsGroupIdPutRequestMembersInner {
	return v.value
}

func (v *NullableGroupsGroupIdPutRequestMembersInner) Set(val *GroupsGroupIdPutRequestMembersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupsGroupIdPutRequestMembersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupsGroupIdPutRequestMembersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupsGroupIdPutRequestMembersInner(val *GroupsGroupIdPutRequestMembersInner) *NullableGroupsGroupIdPutRequestMembersInner {
	return &NullableGroupsGroupIdPutRequestMembersInner{value: val, isSet: true}
}

func (v NullableGroupsGroupIdPutRequestMembersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupsGroupIdPutRequestMembersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


