/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the SpacesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpacesPost200Response{}

// SpacesPost200Response struct for SpacesPost200Response
type SpacesPost200Response struct {
	// API request succeeded
	Success bool `json:"success"`
	Data SpacesPost200ResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SpacesPost200Response SpacesPost200Response

// NewSpacesPost200Response instantiates a new SpacesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpacesPost200Response(success bool, data SpacesPost200ResponseData) *SpacesPost200Response {
	this := SpacesPost200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewSpacesPost200ResponseWithDefaults instantiates a new SpacesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpacesPost200ResponseWithDefaults() *SpacesPost200Response {
	this := SpacesPost200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *SpacesPost200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *SpacesPost200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *SpacesPost200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *SpacesPost200Response) GetData() SpacesPost200ResponseData {
	if o == nil {
		var ret SpacesPost200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SpacesPost200Response) GetDataOk() (*SpacesPost200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SpacesPost200Response) SetData(v SpacesPost200ResponseData) {
	o.Data = v
}

func (o SpacesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpacesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SpacesPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpacesPost200Response := _SpacesPost200Response{}

	err = json.Unmarshal(data, &varSpacesPost200Response)

	if err != nil {
		return err
	}

	*o = SpacesPost200Response(varSpacesPost200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSpacesPost200Response struct {
	value *SpacesPost200Response
	isSet bool
}

func (v NullableSpacesPost200Response) Get() *SpacesPost200Response {
	return v.value
}

func (v *NullableSpacesPost200Response) Set(val *SpacesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSpacesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSpacesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpacesPost200Response(val *SpacesPost200Response) *NullableSpacesPost200Response {
	return &NullableSpacesPost200Response{value: val, isSet: true}
}

func (v NullableSpacesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpacesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


