/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease The release version to set for the specified element in the named release manifest
type SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease struct {
	value *SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease
	isSet bool
}

func (v NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) Get() *SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease {
	return v.value
}

func (v *NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) Set(val *SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease(val *SourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) *NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease {
	return &NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease{value: val, isSet: true}
}

func (v NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceControlManifestsManifestNameAppsAppUuidPutRequestRelease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


