/*
Retool API

The Retool API enables you to programmatically perform actions across your organization and its spaces. You can perform RESTful requests to manage a wide range of objects, such as adding users or updating resource configurations.  ## Base URL  All endpoints are relative to your Retool instance URL:  ``` https://{your-retool-instance}/api/v2 ```  ## Authentication  The Retool API uses HTTP Bearer authentication scheme with API tokens to authenticate requests. Users with sufficient permissions can create API tokens in the organization's [Retool API settings](/auth/login?redirectOnLogin=settings/api). Each token can be scoped to specific permissions—only grant the scopes needed for your use case.  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Versioning  The API version corresponds to the Retool release version in which it was shipped. This means the API version reflects the features and endpoints available in that release. When you upgrade your Retool instance, the API version updates alongside it and any new endpoints or capabilities introduced in that release become available.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RestAPIOptionsAuthenticationOptionsAnyOf10 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestAPIOptionsAuthenticationOptionsAnyOf10{}

// RestAPIOptionsAuthenticationOptionsAnyOf10 struct for RestAPIOptionsAuthenticationOptionsAnyOf10
type RestAPIOptionsAuthenticationOptionsAnyOf10 struct {
	AuthenticationType string `json:"authentication_type"`
	SessionCookieName string `json:"session_cookie_name"`
	VerifySessionUrl string `json:"verify_session_url"`
}

type _RestAPIOptionsAuthenticationOptionsAnyOf10 RestAPIOptionsAuthenticationOptionsAnyOf10

// NewRestAPIOptionsAuthenticationOptionsAnyOf10 instantiates a new RestAPIOptionsAuthenticationOptionsAnyOf10 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestAPIOptionsAuthenticationOptionsAnyOf10(authenticationType string, sessionCookieName string, verifySessionUrl string) *RestAPIOptionsAuthenticationOptionsAnyOf10 {
	this := RestAPIOptionsAuthenticationOptionsAnyOf10{}
	this.AuthenticationType = authenticationType
	this.SessionCookieName = sessionCookieName
	this.VerifySessionUrl = verifySessionUrl
	return &this
}

// NewRestAPIOptionsAuthenticationOptionsAnyOf10WithDefaults instantiates a new RestAPIOptionsAuthenticationOptionsAnyOf10 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestAPIOptionsAuthenticationOptionsAnyOf10WithDefaults() *RestAPIOptionsAuthenticationOptionsAnyOf10 {
	this := RestAPIOptionsAuthenticationOptionsAnyOf10{}
	return &this
}

// GetAuthenticationType returns the AuthenticationType field value
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) GetAuthenticationType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationType
}

// GetAuthenticationTypeOk returns a tuple with the AuthenticationType field value
// and a boolean to check if the value has been set.
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) GetAuthenticationTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationType, true
}

// SetAuthenticationType sets field value
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) SetAuthenticationType(v string) {
	o.AuthenticationType = v
}

// GetSessionCookieName returns the SessionCookieName field value
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) GetSessionCookieName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionCookieName
}

// GetSessionCookieNameOk returns a tuple with the SessionCookieName field value
// and a boolean to check if the value has been set.
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) GetSessionCookieNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionCookieName, true
}

// SetSessionCookieName sets field value
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) SetSessionCookieName(v string) {
	o.SessionCookieName = v
}

// GetVerifySessionUrl returns the VerifySessionUrl field value
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) GetVerifySessionUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerifySessionUrl
}

// GetVerifySessionUrlOk returns a tuple with the VerifySessionUrl field value
// and a boolean to check if the value has been set.
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) GetVerifySessionUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifySessionUrl, true
}

// SetVerifySessionUrl sets field value
func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) SetVerifySessionUrl(v string) {
	o.VerifySessionUrl = v
}

func (o RestAPIOptionsAuthenticationOptionsAnyOf10) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestAPIOptionsAuthenticationOptionsAnyOf10) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authentication_type"] = o.AuthenticationType
	toSerialize["session_cookie_name"] = o.SessionCookieName
	toSerialize["verify_session_url"] = o.VerifySessionUrl
	return toSerialize, nil
}

func (o *RestAPIOptionsAuthenticationOptionsAnyOf10) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authentication_type",
		"session_cookie_name",
		"verify_session_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestAPIOptionsAuthenticationOptionsAnyOf10 := _RestAPIOptionsAuthenticationOptionsAnyOf10{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestAPIOptionsAuthenticationOptionsAnyOf10)

	if err != nil {
		return err
	}

	*o = RestAPIOptionsAuthenticationOptionsAnyOf10(varRestAPIOptionsAuthenticationOptionsAnyOf10)

	return err
}

type NullableRestAPIOptionsAuthenticationOptionsAnyOf10 struct {
	value *RestAPIOptionsAuthenticationOptionsAnyOf10
	isSet bool
}

func (v NullableRestAPIOptionsAuthenticationOptionsAnyOf10) Get() *RestAPIOptionsAuthenticationOptionsAnyOf10 {
	return v.value
}

func (v *NullableRestAPIOptionsAuthenticationOptionsAnyOf10) Set(val *RestAPIOptionsAuthenticationOptionsAnyOf10) {
	v.value = val
	v.isSet = true
}

func (v NullableRestAPIOptionsAuthenticationOptionsAnyOf10) IsSet() bool {
	return v.isSet
}

func (v *NullableRestAPIOptionsAuthenticationOptionsAnyOf10) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestAPIOptionsAuthenticationOptionsAnyOf10(val *RestAPIOptionsAuthenticationOptionsAnyOf10) *NullableRestAPIOptionsAuthenticationOptionsAnyOf10 {
	return &NullableRestAPIOptionsAuthenticationOptionsAnyOf10{value: val, isSet: true}
}

func (v NullableRestAPIOptionsAuthenticationOptionsAnyOf10) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestAPIOptionsAuthenticationOptionsAnyOf10) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


