/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf{}

// UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf struct for UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf
type UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf struct {
	Type string `json:"type"`
	Id float32 `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf

// NewUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf instantiates a new UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf(type_ string, id float32) *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf {
	this := UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOfWithDefaults instantiates a new UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOfWithDefaults() *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf {
	this := UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf{}
	return &this
}

// GetType returns the Type field value
func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) SetId(v float32) {
	o.Id = v
}

func (o UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf := _UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf{}

	err = json.Unmarshal(data, &varUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf)

	if err != nil {
		return err
	}

	*o = UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf(varUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf struct {
	value *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf
	isSet bool
}

func (v NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) Get() *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf {
	return v.value
}

func (v *NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) Set(val *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf(val *UserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) *NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf {
	return &NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf{value: val, isSet: true}
}

func (v NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTasksTaskIdReassignPatchRequestAssigneesInnerAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


