/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AccessTokensAccessTokenIdGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessTokensAccessTokenIdGet200ResponseData{}

// AccessTokensAccessTokenIdGet200ResponseData The requested access token.
type AccessTokensAccessTokenIdGet200ResponseData struct {
	// The uuid of the access token.
	Id string `json:"id"`
	// The name of the access token.
	Label string `json:"label"`
	// The description of the access token.
	Description NullableString `json:"description"`
	// Last 4 characters of the access token secret
	Last4 string `json:"last4"`
	// The legacy id of the user that created the token
	OwnerLegacyId float32 `json:"owner_legacy_id"`
	Scopes []string `json:"scopes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _AccessTokensAccessTokenIdGet200ResponseData AccessTokensAccessTokenIdGet200ResponseData

// NewAccessTokensAccessTokenIdGet200ResponseData instantiates a new AccessTokensAccessTokenIdGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessTokensAccessTokenIdGet200ResponseData(id string, label string, description NullableString, last4 string, ownerLegacyId float32, scopes []string, createdAt time.Time, updatedAt time.Time) *AccessTokensAccessTokenIdGet200ResponseData {
	this := AccessTokensAccessTokenIdGet200ResponseData{}
	this.Id = id
	this.Label = label
	this.Description = description
	this.Last4 = last4
	this.OwnerLegacyId = ownerLegacyId
	this.Scopes = scopes
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewAccessTokensAccessTokenIdGet200ResponseDataWithDefaults instantiates a new AccessTokensAccessTokenIdGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessTokensAccessTokenIdGet200ResponseDataWithDefaults() *AccessTokensAccessTokenIdGet200ResponseData {
	this := AccessTokensAccessTokenIdGet200ResponseData{}
	return &this
}

// GetId returns the Id field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetLabel(v string) {
	o.Label = v
}

// GetDescription returns the Description field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}

	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// SetDescription sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetDescription(v string) {
	o.Description.Set(&v)
}

// GetLast4 returns the Last4 field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetLast4() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Last4
}

// GetLast4Ok returns a tuple with the Last4 field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetLast4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last4, true
}

// SetLast4 sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetLast4(v string) {
	o.Last4 = v
}

// GetOwnerLegacyId returns the OwnerLegacyId field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetOwnerLegacyId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OwnerLegacyId
}

// GetOwnerLegacyIdOk returns a tuple with the OwnerLegacyId field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetOwnerLegacyIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerLegacyId, true
}

// SetOwnerLegacyId sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetOwnerLegacyId(v float32) {
	o.OwnerLegacyId = v
}

// GetScopes returns the Scopes field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetScopesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetScopes(v []string) {
	o.Scopes = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AccessTokensAccessTokenIdGet200ResponseData) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AccessTokensAccessTokenIdGet200ResponseData) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o AccessTokensAccessTokenIdGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessTokensAccessTokenIdGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["description"] = o.Description.Get()
	toSerialize["last4"] = o.Last4
	toSerialize["owner_legacy_id"] = o.OwnerLegacyId
	toSerialize["scopes"] = o.Scopes
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *AccessTokensAccessTokenIdGet200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
		"description",
		"last4",
		"owner_legacy_id",
		"scopes",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessTokensAccessTokenIdGet200ResponseData := _AccessTokensAccessTokenIdGet200ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccessTokensAccessTokenIdGet200ResponseData)

	if err != nil {
		return err
	}

	*o = AccessTokensAccessTokenIdGet200ResponseData(varAccessTokensAccessTokenIdGet200ResponseData)

	return err
}

type NullableAccessTokensAccessTokenIdGet200ResponseData struct {
	value *AccessTokensAccessTokenIdGet200ResponseData
	isSet bool
}

func (v NullableAccessTokensAccessTokenIdGet200ResponseData) Get() *AccessTokensAccessTokenIdGet200ResponseData {
	return v.value
}

func (v *NullableAccessTokensAccessTokenIdGet200ResponseData) Set(val *AccessTokensAccessTokenIdGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessTokensAccessTokenIdGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessTokensAccessTokenIdGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessTokensAccessTokenIdGet200ResponseData(val *AccessTokensAccessTokenIdGet200ResponseData) *NullableAccessTokensAccessTokenIdGet200ResponseData {
	return &NullableAccessTokensAccessTokenIdGet200ResponseData{value: val, isSet: true}
}

func (v NullableAccessTokensAccessTokenIdGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessTokensAccessTokenIdGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


