/*
Retool API

Go to Settings > API to get started. Once you generate an API token, use bearer token authentication to make requests.

API version: 2.12.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner{}

// PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner struct for PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner
type PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner struct {
	Subject PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSubject `json:"subject"`
	Sources *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSources `json:"sources,omitempty"`
	AccessLevel string `json:"accessLevel"`
	AdditionalProperties map[string]interface{}
}

type _PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner

// NewPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner instantiates a new PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner(subject PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSubject, accessLevel string) *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner {
	this := PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner{}
	this.Subject = subject
	this.AccessLevel = accessLevel
	return &this
}

// NewPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerWithDefaults instantiates a new PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerWithDefaults() *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner {
	this := PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner{}
	return &this
}

// GetSubject returns the Subject field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) GetSubject() PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSubject {
	if o == nil {
		var ret PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSubject
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) GetSubjectOk() (*PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSubject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) SetSubject(v PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSubject) {
	o.Subject = v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) GetSources() PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSources {
	if o == nil || IsNil(o.Sources) {
		var ret PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSources
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) GetSourcesOk() (*PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSources, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSources and assigns it to the Sources field.
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) SetSources(v PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInnerSources) {
	o.Sources = &v
}

// GetAccessLevel returns the AccessLevel field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) GetAccessLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessLevel
}

// GetAccessLevelOk returns a tuple with the AccessLevel field value
// and a boolean to check if the value has been set.
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) GetAccessLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessLevel, true
}

// SetAccessLevel sets field value
func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) SetAccessLevel(v string) {
	o.AccessLevel = v
}

func (o PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject"] = o.Subject
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	toSerialize["accessLevel"] = o.AccessLevel

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject",
		"accessLevel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner := _PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner{}

	err = json.Unmarshal(data, &varPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner)

	if err != nil {
		return err
	}

	*o = PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner(varPermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subject")
		delete(additionalProperties, "sources")
		delete(additionalProperties, "accessLevel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner struct {
	value *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner
	isSet bool
}

func (v NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) Get() *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner {
	return v.value
}

func (v *NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) Set(val *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner(val *PermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) *NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner {
	return &NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner{value: val, isSet: true}
}

func (v NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionsAccessListObjectTypeObjectIdGet200ResponseDataGroupInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


